title: 无垠喵の小窝
description: > # this means to ignore newlines until "baseurl:"
  纸张与笔尖将光阴剪裁<br>星光终在梦的结尾盛开<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pages.gqkitten.dpdns.org/blog" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: '柳无垠'
  last_name: '柳'
  cv: '//kaptn.ru'
  avatar: ''
  github_username:  gqkitten  
  email: a3045132338@outlook.com
  # vk_id: id201664979
  # telegram_name: vikapitoshka 
  # logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


